import { Vehicle, Service } from './types';

export const COMPANY_INFO = {
  name: 'AUTO ANI',
  tagline: 'Premium Auto Salon - Partneri Juaj i Besuar që nga 2015',
  phone: '+38349204242',
  whatsapp: '+38349204242',
  email: 'aniautosallon@gmail.com',
  address: 'Gazmend Baliu, Mitrovicë, Kosovë 40000',
  hours: {
    weekdays: '09:00 - 19:00',
    saturday: '09:00 - 17:00',
    sunday: 'Closed'
  },
  social: {
    facebook: 'https://www.facebook.com/autosallonani',
    instagram: 'https://instagram.com/autoani',
    twitter: 'https://twitter.com/autoani',
    linkedin: 'https://linkedin.com/company/autoani'
  },
  stats: {
    yearsInBusiness: 9,
    vehiclesSold: 2500,
    satisfiedCustomers: 2300,
    googleRating: 4.8,
    googleReviews: 156
  }
};

export const NAVIGATION_LINKS = [
  { href: '/', label: 'Ballina' },
  { href: '/vehicles', label: 'Automjetet' },
  { href: '/services', label: 'Shërbimet' },
  { href: '/about', label: 'Rreth Nesh' },
  { href: '/contact', label: 'Kontakti' },
  { href: '/compare', label: 'Krahasoni' }
];

export const VEHICLES: Vehicle[] = [
  {
    id: 'audi-q5-2020',
    make: 'Audi',
    model: 'Q5 Business Sport',
    year: 2020,
    price: 26500,
    mileage: 220000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Gray',
    engineSize: '2.0L',
    drivetrain: 'Quattro AWD',
    features: [
      '163 PS Quattro 🇫🇮',
      'Distance Control',
      'Kamera',
      'Lane Assist',
      '3 Çelësa dhe Webasto',
      'Business Sport Paketë',
      'Importuar nga Finlanda'
    ],
    images: [
      '/images/vehicles/audi-q5-2020/1.jpg',
      '/images/vehicles/audi-q5-2020/2.jpg',
      '/images/vehicles/audi-q5-2020/3.jpg',
      '/images/vehicles/audi-q5-2020/4.jpg',
      '/images/vehicles/audi-q5-2020/5.jpg',
      '/images/vehicles/audi-q5-2020/6.jpg',
      '/images/vehicles/audi-q5-2020/7.jpg',
      '/images/vehicles/audi-q5-2020/8.jpg',
      '/images/vehicles/audi-q5-2020/9.jpg',
      '/images/vehicles/audi-q5-2020/10.jpg',
      '/images/vehicles/audi-q5-2020/11.jpg',
      '/images/vehicles/audi-q5-2020/12.jpg',
      '/images/vehicles/audi-q5-2020/13.jpg',
      '/images/vehicles/audi-q5-2020/14.jpg',
      '/images/vehicles/audi-q5-2020/15.jpg'
    ],
    description: 'Audi Q5 Business Sport 2020 nga Finlanda 🇫🇮. Motor 2.0L 163 PS Quattro, 220,000 km. Me Distance Control, kamera, Lane Assist, webasto dhe 3 çelësa. Import direkt nga Finlanda!',
    featured: true,
    status: 'I Disponueshëm',
    doors: 5,
    seats: 5,
    mpgCity: 28,
    mpgHighway: 38
  },
  {
    id: 'skoda-superb-2020',
    make: 'Skoda',
    model: 'Superb Style Business Line Facelift',
    year: 2020,
    price: 22500,
    mileage: 300000,
    fuelType: 'Diesel',
    transmission: 'DSG Automatic',
    bodyType: 'Sedan',
    color: 'White',
    engineSize: '2.0L',
    drivetrain: 'FWD',
    features: [
      'Matrix LED Automatike',
      'Digital Cockpit',
      'Ulëse me Nxemje Para/Prapa',
      'Ulëse me Rrym dhe Memorie',
      'Timon me Nxemje',
      'Webasto dhe 3 Çelësa',
      'Sistem Canton',
      'LED Ambient 10 Ngjyra',
      'Line Assist',
      'Distance Control',
      'Drive Select',
      'Kamera 360°',
      'Start/Stop pa Çelës',
      'Navigacion i Madh',
      'Air Care'
    ],
    images: [
      '/images/vehicles/skoda-superb-2020/1.jpg',
      '/images/vehicles/skoda-superb-2020/2.jpg',
      '/images/vehicles/skoda-superb-2020/3.jpg',
      '/images/vehicles/skoda-superb-2020/4.jpg',
      '/images/vehicles/skoda-superb-2020/5.jpg',
      '/images/vehicles/skoda-superb-2020/6.jpg',
      '/images/vehicles/skoda-superb-2020/7.jpg',
      '/images/vehicles/skoda-superb-2020/8.jpg',
      '/images/vehicles/skoda-superb-2020/9.jpg',
      '/images/vehicles/skoda-superb-2020/10.jpg',
      '/images/vehicles/skoda-superb-2020/11.jpg',
      '/images/vehicles/skoda-superb-2020/12.jpg',
      '/images/vehicles/skoda-superb-2020/13.jpg',
      '/images/vehicles/skoda-superb-2020/14.jpg',
      '/images/vehicles/skoda-superb-2020/15.jpg',
      '/images/vehicles/skoda-superb-2020/16.jpg',
      '/images/vehicles/skoda-superb-2020/17.jpg'
    ],
    description: 'Skoda Superb Style Business Line Facelift 2020 me Matrix LED. Digital cockpit, 300,000 km (rrypi i ndërruar dhe servisi i kryer). Ulëse të ngrohta, webasto, sistem Canton, dhe teknologji premium. Gjendje perfekte!',
    featured: true,
    status: 'I Disponueshëm',
    doors: 4,
    seats: 5,
    mpgCity: 30,
    mpgHighway: 45
  },
  {
    id: 'peugeot-3008-premium-2018',
    make: 'Peugeot',
    model: '3008 Premium Allure',
    year: 2018,
    price: 15900,
    mileage: 250000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Gray',
    engineSize: '1.5L',
    drivetrain: 'FWD',
    features: [
      'Digital Cockpit',
      '131 PS Automatik',
      'Premium Allure Paketë',
      'Serviset në Peugeot',
      'Opsion pa Doganë',
      'Sistemet e Sigurisë',
      'Navigacion',
      'Klimë Automatike'
    ],
    images: [
      '/images/vehicles/peugeot-3008-premium-2018/1.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/2.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/3.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/4.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/5.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/6.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/7.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/8.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/9.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/10.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/11.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/12.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/13.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/14.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/15.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/16.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/17.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/18.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/19.jpg',
      '/images/vehicles/peugeot-3008-premium-2018/20.jpg'
    ],
    description: 'Peugeot 3008 Premium Allure 2018 me Digital Cockpit. Motor 1.5L Diesel Automatik 131 PS. 250,000 km (serviset e kryer në Peugeot). Çmimi me doganë €15,900 - shitet edhe pa doganë.',
    featured: true,
    status: 'I Disponueshëm',
    doors: 5,
    seats: 5,
    mpgCity: 35,
    mpgHighway: 50
  },
  {
    id: 'audi-a4-s-line-2015',
    make: 'Audi',
    model: 'A4 S-Line',
    year: 2015,
    price: 13500,
    mileage: 250000,
    fuelType: 'Diesel',
    transmission: 'Manual',
    bodyType: 'Sedan',
    color: 'Silver',
    engineSize: '2.0L',
    drivetrain: 'Quattro AWD',
    features: [
      '190 PS Quattro',
      'Drive Select (Comfort/Auto/Dynamic)',
      'Ulëse Alcantara me Nxemje',
      'Klimë 2 Zonale Digjitale',
      'AdBlue',
      'Auto Hold',
      'Sensorë Parkimi 360°',
      'Sensorë Shiu',
      'Tempomat',
      'Histori në Audi'
    ],
    images: [
      '/images/vehicles/audi-a4-s-line-2015/1.jpg',
      '/images/vehicles/audi-a4-s-line-2015/2.jpg',
      '/images/vehicles/audi-a4-s-line-2015/3.jpg',
      '/images/vehicles/audi-a4-s-line-2015/4.jpg',
      '/images/vehicles/audi-a4-s-line-2015/5.jpg',
      '/images/vehicles/audi-a4-s-line-2015/6.jpg',
      '/images/vehicles/audi-a4-s-line-2015/7.jpg',
      '/images/vehicles/audi-a4-s-line-2015/8.jpg',
      '/images/vehicles/audi-a4-s-line-2015/9.jpg',
      '/images/vehicles/audi-a4-s-line-2015/10.jpg'
    ],
    description: 'Audi A4 S-Line 2015 pa doganë. 250,000 km me histori në Audi. Motor 2.0L 190 PS Quattro (motori i modelit të ri). Me Drive Select, ulëse Alcantara të ngrohta, dhe shumë pajisje premium.',
    featured: true,
    status: 'I Disponueshëm',
    doors: 4,
    seats: 5,
    mpgCity: 32,
    mpgHighway: 45
  },
  {
    id: 'skoda-superb-2018',
    make: 'Skoda',
    model: 'Superb Style Business Line',
    year: 2018,
    price: 16500,
    mileage: 270000,
    fuelType: 'Diesel',
    transmission: 'DSG Automatic',
    bodyType: 'Sedan',
    color: 'Dark Blue',
    engineSize: '2.0L',
    drivetrain: 'FWD',
    features: [
      'Ulëse Alcantara me Nxemje',
      'Ulëse me Rrym dhe Memorie',
      'Timon me Nxemje',
      'Start/Stop pa Çelës',
      'Webasto dhe 3 Çelësa',
      'Drita LED Automatike',
      'Sistem Canton',
      'LED Ambient 10 Ngjyra',
      'Line Assist',
      'Distance Control',
      'Drive Select',
      'Air Care',
      'Ad-Blue',
      'Navigacion i Madh',
      'Kamera 360°'
    ],
    images: [
      '/images/vehicles/skoda-superb-2018/1.jpg',
      '/images/vehicles/skoda-superb-2018/2.jpg',
      '/images/vehicles/skoda-superb-2018/3.jpg',
      '/images/vehicles/skoda-superb-2018/4.jpg',
      '/images/vehicles/skoda-superb-2018/5.jpg',
      '/images/vehicles/skoda-superb-2018/6.jpg',
      '/images/vehicles/skoda-superb-2018/7.jpg',
      '/images/vehicles/skoda-superb-2018/8.jpg',
      '/images/vehicles/skoda-superb-2018/9.jpg',
      '/images/vehicles/skoda-superb-2018/10.jpg',
      '/images/vehicles/skoda-superb-2018/11.jpg',
      '/images/vehicles/skoda-superb-2018/12.jpg',
      '/images/vehicles/skoda-superb-2018/13.jpg',
      '/images/vehicles/skoda-superb-2018/14.jpg',
      '/images/vehicles/skoda-superb-2018/15.jpg',
      '/images/vehicles/skoda-superb-2018/16.jpg'
    ],
    description: 'Skoda Superb Style Business Line 2.0 DSG 2018. 270,000 km (rrypi i ndërruar dhe servisi i kryer). Me ulëse Alcantara të ngrohta, webasto, sistem Canton, dhe shumë pajisje luksoze. €16,500 me doganë.',
    featured: true,
    status: 'I Disponueshëm',
    doors: 4,
    seats: 5,
    mpgCity: 28,
    mpgHighway: 40
  },
  {
    id: 'vw-passat-b8-2016',
    make: 'Volkswagen',
    model: 'Passat B8 Comfortline',
    year: 2016,
    price: 14500,
    mileage: 277000,
    fuelType: 'Diesel',
    transmission: 'DSG Automatic',
    bodyType: 'Sedan',
    color: 'Silver',
    engineSize: '1.6L',
    drivetrain: 'FWD',
    features: ['Drita LED', 'Ulëse të Ngrohta', 'Klimë 3 Zonale', 'Auto Hold', 'Sensorë Parkimi 360°', 'Dy Çelësa'],
    images: [
      '/images/vehicles/vw-passat-b8-2016/1.jpg',
      '/images/vehicles/vw-passat-b8-2016/2.jpg',
      '/images/vehicles/vw-passat-b8-2016/3.jpg',
      '/images/vehicles/vw-passat-b8-2016/4.jpg',
      '/images/vehicles/vw-passat-b8-2016/5.jpg',
      '/images/vehicles/vw-passat-b8-2016/6.jpg',
      '/images/vehicles/vw-passat-b8-2016/7.jpg',
      '/images/vehicles/vw-passat-b8-2016/8.jpg',
      '/images/vehicles/vw-passat-b8-2016/9.jpg',
      '/images/vehicles/vw-passat-b8-2016/10.jpg',
      '/images/vehicles/vw-passat-b8-2016/11.jpg'
    ],
    description: 'VW Passat B8 1.6 DSG Comfortline 2016. Mirë e mbajtur me 277,000 km. Me drita LED, ulëse të ngrohta, klimë 3 zonale, auto hold, dhe sensorë parkimi 360°. Vjen me dy çelësa.',
    featured: true,
    status: 'I Disponueshëm',
    doors: 4,
    seats: 5,
    mpgCity: 30,
    mpgHighway: 42
  },
  {
    id: 'golf-7-gtd-2017',
    make: 'Volkswagen',
    model: 'Golf 7 GTD',
    year: 2017,
    price: 18500,
    mileage: 255000,
    fuelType: 'Diesel',
    transmission: 'DSG Automatic',
    bodyType: 'Hatchback',
    color: 'Dark Blue',
    engineSize: '2.0L',
    drivetrain: 'FWD',
    features: ['Çati Panoramike', 'Kokpit Digjital', 'Paketë GTD Sport', '184 PS'],
    images: [
      '/images/vehicles/golf-7-gtd-2017/1.jpg',
      '/images/vehicles/golf-7-gtd-2017/2.jpg',
      '/images/vehicles/golf-7-gtd-2017/3.jpg',
      '/images/vehicles/golf-7-gtd-2017/4.jpg',
      '/images/vehicles/golf-7-gtd-2017/5.jpg',
      '/images/vehicles/golf-7-gtd-2017/6.jpg',
      '/images/vehicles/golf-7-gtd-2017/7.jpg',
      '/images/vehicles/golf-7-gtd-2017/8.jpg',
      '/images/vehicles/golf-7-gtd-2017/9.jpg',
      '/images/vehicles/golf-7-gtd-2017/10.jpg',
      '/images/vehicles/golf-7-gtd-2017/11.jpg',
      '/images/vehicles/golf-7-gtd-2017/12.jpg',
      '/images/vehicles/golf-7-gtd-2017/13.jpg',
      '/images/vehicles/golf-7-gtd-2017/14.jpg'
    ],
    description: 'Golf 7 Facelift GTD 2.0 DSG, regjistruar RKS. 184 PS, Nëntor 2017, 255,000 km. Me çati panoramike dhe kokpit digjital. Gjendje e shkëlqyer!',
    featured: true,
    status: 'I Disponueshëm',
    doors: 5,
    seats: 5,
    mpgCity: 35,
    mpgHighway: 45
  }
];

export const SERVICES_DATA: Service[] = [
  {
    id: '1',
    title: 'Vehicle Sales',
    description: 'Wide selection of new and certified pre-owned vehicles from premium brands',
    icon: 'car',
    features: ['Quality certified vehicles', 'Competitive pricing', 'Full service history', 'Extended warranty options']
  },
  {
    id: '2',
    title: 'Financing',
    description: 'Flexible financing options with competitive rates - 0% financing available on selected models',
    icon: 'calculator',
    features: ['0% financing available', 'Quick approval', 'Flexible terms', 'Online application']
  },
  {
    id: '3',
    title: 'Trade-In',
    description: 'Fair market value for your current vehicle with €1000 Trade-In Bonus promotion',
    icon: 'refresh-cw',
    features: ['Fair market valuation', '€1000 bonus promotion', 'Instant evaluation', 'Easy process']
  },
  {
    id: '4',
    title: 'Vehicle Import',
    description: 'Professional import services from EU countries with all documentation handled',
    icon: 'truck',
    features: ['EU-wide sourcing', 'Documentation handling', 'Transport arranged', 'Customs clearance']
  },
  {
    id: '5',
    title: 'Insurance Assistance',
    description: 'Help with vehicle insurance and registration - making the process seamless',
    icon: 'shield',
    features: ['Insurance consultation', 'Registration assistance', 'Partner network', 'Best rates']
  },
  {
    id: '6',
    title: 'After-Sales Service',
    description: 'Comprehensive warranty and maintenance packages for your peace of mind',
    icon: 'wrench',
    features: ['Extended warranty', 'Maintenance packages', 'Genuine parts', '24/7 support']
  }
];

export const VEHICLE_MAKES = ['Mercedes-Benz', 'BMW', 'Audi', 'Volkswagen', 'Tesla', 'Toyota', 'Ford', 'Honda', 'Nissan', 'Chevrolet', 'Mazda', 'Hyundai', 'Lexus', 'Kia', 'Subaru', 'Jeep', 'Genesis', 'Mitsubishi', 'Volvo'];
export const FUEL_TYPES = ['Gasoline', 'Diesel', 'Electric', 'Hybrid'];
export const TRANSMISSION_TYPES = ['Manual', 'Automatic', 'CVT'];
export const BODY_TYPES = ['Sedan', 'SUV', 'Truck', 'Coupe', 'Hatchback', 'Van'];