#!/bin/bash

# This script sets environment variables using the Render API
# You need to set your RENDER_API_KEY first

SERVICE_ID="srv-d3hudq8gjchc73aq6ndg"

echo "======================================="
echo "IMPORTANT: Setting Environment Variables on Render"
echo "======================================="
echo ""
echo "Since the Render CLI doesn't support setting environment variables directly,"
echo "you need to set them manually in the Render Dashboard."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://dashboard.render.com/web/${SERVICE_ID}/env"
echo "2. Click 'Add Environment Variable' and add the following variables:"
echo ""
echo "REQUIRED VARIABLES:"
echo "==================="
echo "NODE_ENV                     = production"
echo "DATABASE_PROVIDER            = postgresql"
echo "DATABASE_URL                 = postgresql://auto_ani_database_user:YJSYWhqW3bQXYfu0aX3qTPuCzVsEt29L@dpg-d3i0pn33fgac73a64kog-a.oregon-postgres.render.com/auto_ani_database"
echo "DIRECT_DATABASE_URL          = postgresql://auto_ani_database_user:YJSYWhqW3bQXYfu0aX3qTPuCzVsEt29L@dpg-d3i0pn33fgac73a64kog-a.oregon-postgres.render.com/auto_ani_database"
echo "NEXTAUTH_URL                 = https://auto-ani-website.onrender.com"
echo "NEXTAUTH_SECRET              = 1Yz1tI/xgcab3HBr3OJz3FFQFDN2HHEBEPiekqiDcwAnXRJZDnLrE+5c8HIHedQk"
echo "JWT_SECRET                   = 1Yz1tI/xgcab3HBr3OJz3FFQFDN2HHEBEPiekqiDcwAnXRJZDnLrE+5c8HIHedQk"
echo ""
echo "PUBLIC VARIABLES:"
echo "================="
echo "NEXT_PUBLIC_SITE_URL         = https://auto-ani-website.onrender.com"
echo "NEXT_PUBLIC_APP_URL          = https://auto-ani-website.onrender.com"
echo "NEXT_PUBLIC_WHATSAPP_NUMBER  = 38349204242"
echo "NEXT_PUBLIC_WHATSAPP_MESSAGE = Hello, I'm interested in your vehicles"
echo "NEXT_TELEMETRY_DISABLED      = 1"
echo ""
echo "EMAIL CONFIGURATION (Replace with real values when ready):"
echo "==========================================================="
echo "RESEND_API_KEY               = re_your_actual_resend_api_key"
echo "FROM_EMAIL                   = contact@autosalonani.com"
echo "ADMIN_EMAIL                  = admin@autosalonani.com"
echo ""
echo "OPTIONAL SERVICES (Add real API keys when ready):"
echo "=================================================="
echo "# Google Maps"
echo "GOOGLE_MAPS_API_KEY          = your_actual_google_maps_key"
echo ""
echo "# Stripe Payments"
echo "STRIPE_SECRET_KEY            = sk_live_your_actual_stripe_secret"
echo "STRIPE_PUBLISHABLE_KEY       = pk_live_your_actual_stripe_publishable"
echo ""
echo "# Twilio SMS"
echo "TWILIO_ACCOUNT_SID           = your_actual_twilio_sid"
echo "TWILIO_AUTH_TOKEN            = your_actual_twilio_token"
echo "TWILIO_PHONE_NUMBER          = +your_actual_twilio_number"
echo ""
echo "# Social Media"
echo "FACEBOOK_ACCESS_TOKEN        = your_actual_facebook_token"
echo "INSTAGRAM_ACCESS_TOKEN       = your_actual_instagram_token"
echo ""
echo "======================================="
echo "After adding all variables, click 'Save Changes'"
echo "Your service will automatically redeploy with the new configuration"
echo "======================================="
echo ""
echo "Direct link to your service's environment variables:"
echo "https://dashboard.render.com/web/${SERVICE_ID}/env"